name: compile app  
on:
  pull_request:
    branches: [ meow ]
  push:
    branches: [ meow ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        platform:
          - iOS Simulator
          - iOS
          - placeholder
    steps:
    - name: checkout
      uses: actions/checkout@main
    - name: xcodebuild
      uses: sersoft-gmbh/xcodebuild-action@v3
      with:
        project: kfd-meow.xcodeproj
        scheme: kfd-meow
        destination: platform=${{ matrix.platform }}
        action: build
        
    - name: make
      run: make -f Makefile
      
    - name: Make Meowbreak Package
        run: make package

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Bootstrap.tipa
          path: ./packages/Meowbreak.tipa
  update-release:
    name: Release .tipa
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Delete old release
      uses: dev-drprasad/delete-tag-and-release@v0.2.1
      with:
        delete_release: true
        tag_name: release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Get artifacts
      uses: actions/download-artifact@v3
      with:
        name: Meowbreak.tipa
    - name: Create new release
      uses: ncipollo/release-action@v1
      with:
        name: Rolling Release
        body: These are automatically updated builds of the latest commit.
        artifacts: Meowbreak.tipa"
        tag: release
        token: ${{ secrets.GITHUB_TOKEN }}
